name: CI
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  schedule:
    # Nightly tests run on master by default:
    #   Scheduled workflows run on the latest commit on the default or base branch.
    #   (from https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule)
    - cron: "0 0 * * *"
    
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    name: ubuntu python ${{ matrix.python-version }}
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup base environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: build
          python-version: ${{ matrix.python-version }}
          environment-file: devtools/ci/gh-actions/conda-envs/ubuntu.yml
          auto-activate-base: false
          miniforge-variant: Mambaforge
          use-mamba: true

      - name: List environment
        shell: bash -l {0}
        run: |
          cd ${{ github.workspace }}
          ls
          mamba list
          
      - name: Install 
        shell: bash -l {0}
        run: |
          cd ${{ github.workspace }}
          mamba list
          ls
          pwd
          pip install .

      - name: Test
        shell: bash -l {0}
        run: |
          cd tests
          pytest -v 

      - run: echo "This job's status is ${{ job.status }}."